### ISSUE TITLE
Final todo's

### ISSUE THREAD

**Issue by tmtenbrink** [remla24-team8/operation#11]
### A1

- [x] Ensure linters are setup in all different repo's (flake8, bandit // also set up maybe JS linter)
- [x] Check that pipeline still works

### A2

- [x] Automatic upload after training (some kind of automation) (Dielof)
- [x] lib-version v1, make sure it used correctly (Dielof)
- [x] Frontend improve formatting of JSON score reply (Dielof)

### A3

- [x] README update properly, check if Prometheus and Grafana are working properly out of the box(Felipe)
- [x] Automatic downloading of dashboard through ansible. (Felipe)
- [x] Excellent: AlertManager, PrometheusRule? (Felipe)
- [x] Make metrics nicer on frontend (Felipe)

### A4

- [x] Readme on the soft fail (Dielof)
- [x] Is muatamorphic test good? (Dielof)
- [x] Improve test in operation, see if output is within a value (integration test) (Tip)

### A5

- [x] Experimental version
- [x] Prometheus setup: continuous experimentation
- [x] Istio traffic management (Tip)
- [x] Istio additional use case (rate limiting) (Tip)

### Report

**Comment by diebolo** [comment]
All tasks done!
